name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: yarn install
        run: yarn install
      - name: build test
        run: yarn build


